### ISSUE TITLE
Birth Year Field

### ISSUE THREAD

**Issue by AlanSwenson** [Studio-Center/sc-auditions#1]
Currently we are putting the birth year of children in their last name field after their last name.  It would be nice to have an optional birth year field on talent pages. Then we could determine their age based on this and thats how we can decide if talent are children or not and also when they get older it would automatically deem them adults when they are 18+.  If this is implemented we should also get a filter when selecting talent to add to projects or just browsing talent to search kids by age range. ex 7-10 year olds.

**Comment by AlanSwenson** [comment]
I think the best place to display this field would be right before the Gender Field

**Comment by doodersrage** [comment]
New birth year field added. Already displayed it just after last name code.

**Comment by AlanSwenson** [comment]
can we add it to
![Screen Shot 2019-05-17 at 2 26 11 PM](https://user-images.githubusercontent.com/4286252/57948511-d8000280-78af-11e9-98e3-3396fcf52927.png)
as well?  Right now they are just adding it in the Name field like shown, can we have it display `Name - Birthyear` ?

**Comment by AlanSwenson** [comment]
in the above example. it would be **Lea Dell - 2005** assuming someone enters `2005` into the birthyear field

**Comment by doodersrage** [comment]
That's the way I just programmed it to be for output. First name, last name, then birth year.

**Comment by AlanSwenson** [comment]
cool, just tested it and works perfect!

**Comment by doodersrage** [comment]
added to repo
