### ISSUE TITLE
Getting an error trying to use my new Email Assigned feature

### ISSUE THREAD

**Issue by AlanSwenson** [Studio-Center/sc-auditions#10]
Can you check this out when you get time.  This is what I am getting after about a min or 2 when I try my Email Assigned talent.

![Screen Shot 2019-06-10 at 3 27 14 PM](https://user-images.githubusercontent.com/4286252/59221088-7708d900-8b94-11e9-8431-8b1acc5acb9f.png)
![Screen Shot 2019-06-10 at 3 27 42 PM](https://user-images.githubusercontent.com/4286252/59221093-7a03c980-8b94-11e9-816e-859c1edf7393.png)

**Comment by doodersrage** [comment]
How are you triggering the sendTalentEmail method?

**Comment by AlanSwenson** [comment]
step one: click Email Assigned
step two: fill in subject and body
step three: click send

**Comment by AlanSwenson** [comment]
It seems that the people are emailed, or maybe most of them are... As I got
some responses

**Comment by doodersrage** [comment]
That method is called by various other methods to send talent emails, not sure immediately where it originates. Do the send talent email tool? https://studiocenterauditions.com/#!/tools/email-talent

**Comment by AlanSwenson** [comment]
yup. thats what I am talking about.  sorry.

**Comment by doodersrage** [comment]
I think this error is triggering due to talent's not having email designated as primary contact method then having an error generated.

**Comment by doodersrage** [comment]
Email talent tool updated to only list talent with email assigned as primary contact method. The email all talent checkout also filters out talent with email designated as primary contact now.

**Comment by AlanSwenson** [comment]
Excellent.
