### ISSUE TITLE
Can't click on a number page in Project Browse

### ISSUE THREAD

**Issue by AlanSwenson** [Studio-Center/sc-auditions#12]
@doodersrage 
There is a bug where I can't use the numbers to browse old projects.

Steps to replicate.

Go to Projects/browse,
Click any number besides 1 or 2.

![Screen Shot 2019-07-03 at 10 03 10 AM](https://user-images.githubusercontent.com/4286252/60598071-111a0680-9d7a-11e9-8e7d-01e3f686cb9a.png)
![Screen Shot 2019-07-03 at 10 03 02 AM](https://user-images.githubusercontent.com/4286252/60598072-111a0680-9d7a-11e9-9082-4a721f18d4c6.png)

**Comment by doodersrage** [comment]
Only occurs when Mongoose skip value >= 1000.

**Comment by doodersrage** [comment]
Fix required updating MongoDB sort order cache from default 32MB. Increased to 50MB (partially solved it) then upped to 128MB which appears to have solved it for all archived projects.

Mongo declarations to fix this problem:
use admin
db.adminCommand({setParameter: 1, internalQueryExecMaxBlockingSortBytes:134217728});
