### ISSUE TITLE
Assigned Producer Report

### ISSUE THREAD

**Issue by AlanSwenson** [Studio-Center/sc-auditions#2]
It would be nice to have a report that shows the list of talent that are assigned to a producer based on the "Producer" field on each talent.  It should also show any unassigned talent, so that we know if there are any talent that need to be assigned.

**Comment by doodersrage** [comment]
Started on it, a bit of work left to go. Hopefully I can finish work on it sometime soon.

https://studiocenterauditions.com/#!/reports/assigned-producer

**Comment by doodersrage** [comment]
Report created, uploaded to production and repo.
