### ISSUE TITLE
Centering of Links is off to the left on main page

### ISSUE THREAD

**Issue by AlanSwenson** [Studio-Center/sc-auditions#5]

**Comment by doodersrage** [comment]
Yes, this was done initially to push the logo and buttons away from the mic on the left.

**Comment by AlanSwenson** [comment]
It's these links on the bottom that are weird. IM guessing they are actually centered but the logo and button are pushed over.
![screen shot 2019-03-01 at 3 48 46 pm](https://user-images.githubusercontent.com/4286252/53665529-b3de3f00-3c39-11e9-84be-f24559705bf1.png)

**Comment by doodersrage** [comment]
Yes, those are centered while the items above are offset.
