### ISSUE TITLE
ISDN Source Connect List

### ISSUE THREAD

**Issue by AlanSwenson** [Studio-Center/sc-auditions#8]
This option would be in the "Talent" menu. Following the "New" option.
It would be an alphabetical by First name (or sortable) list that contains a few fields:
Talent Name | ISDN 1 | ISDN 2 | Source Connect Username | Phone Number | Email Address

And it would only list talent that have non-null values for at least 1 of ISDN or Source Connect, but doesn't need to be AND.

**Comment by doodersrage** [comment]
How about I add the ISDN lines to the talent list page then add a checkbox that filters only those talent with ISDN and/or source connect values?

**Comment by AlanSwenson** [comment]
I think that would be information overload.  This is the list i am trying to replace.
![Screen Shot 2019-05-17 at 2 42 17 PM](https://user-images.githubusercontent.com/4286252/57949298-01219280-78b2-11e9-9d32-d98ffe85b5c2.png)
And there is an equally akward one with source connect usernames

**Comment by doodersrage** [comment]
ok

**Comment by doodersrage** [comment]
Is this about what you are asking for?

https://studiocenterauditions.com/#!/reports/isdn-source-connect-list

**Comment by AlanSwenson** [comment]
almost, remove the location column. and move it to tools instead of reports.

**Comment by doodersrage** [comment]
Changes applied.

**Comment by AlanSwenson** [comment]
It looks like only the people with ISDN are on the list, it should also include the people that have only source connect as well.

**Comment by doodersrage** [comment]
It should display either or now.

**Comment by doodersrage** [comment]
added to master, active in production
