### ISSUE TITLE
Feature/ Add a notes field to talent

### ISSUE THREAD

**Issue by AlanSwenson** [Studio-Center/sc-auditions#9]
Currently people are writing notes in things like the last name field or source connect field.  Since there is an apparent need to add notes to certain talent, I think we need a notes field.

**Comment by doodersrage** [comment]
<img width="1227" alt="Screen Shot 2019-06-10 at 4 41 43 PM" src="https://user-images.githubusercontent.com/1476679/59225457-c522da00-8b9e-11e9-95ac-0d5766c32f9f.png">

Note field added to talent pages.
